using Mafi;
using Mafi.Base;
using Mafi.Core.Mods;
using Mafi.Core.Research;

namespace PackingMod;

internal class ExampleResearchData : IResearchNodesData {

	public void RegisterData(ProtoRegistrator registrator) {

		ResearchNodeProto nodeProto = registrator.ResearchNodeProtoBuilder
			.Start("Packing", PackingModIds.Research.UnlockPackingModStuff)
			.Description("Unlocks packing to compress or decompress materials.")
			.AddProductToUnlock(PackingModIds.Products.AnimalFeedCompressed)
			.AddProductToUnlock(PackingModIds.Products.BiomassCompressed)
			.AddProductToUnlock(PackingModIds.Products.CanolaCompressed)
			.AddProductToUnlock(PackingModIds.Products.CoalCompressed)
			.AddProductToUnlock(PackingModIds.Products.CompostCompressed)
			.AddProductToUnlock(PackingModIds.Products.CopperOreCrushedCompressed)
			.AddProductToUnlock(PackingModIds.Products.CopperOreCompressed)
			.AddProductToUnlock(PackingModIds.Products.CornCompressed)
			.AddProductToUnlock(PackingModIds.Products.FilterMediaCompressed)
			.AddProductToUnlock(PackingModIds.Products.GlassMixCompressed)
			.AddProductToUnlock(PackingModIds.Products.GoldOreCrushedCompressed)
			.AddProductToUnlock(PackingModIds.Products.GoldOrePowderCompressed)
			.AddProductToUnlock(PackingModIds.Products.GoldOreCompressed)
			.AddProductToUnlock(PackingModIds.Products.GravelCompressed)
			.AddProductToUnlock(PackingModIds.Products.IronOreCrushedCompressed)
			.AddProductToUnlock(PackingModIds.Products.IronOreCompressed)
			.AddProductToUnlock(PackingModIds.Products.LimestoneCompressed)
			.AddProductToUnlock(PackingModIds.Products.MeatTrimmingsCompressed)
			.AddProductToUnlock(PackingModIds.Products.PoppyCompressed)
			.AddProductToUnlock(PackingModIds.Products.PotatoCompressed)
			.AddProductToUnlock(PackingModIds.Products.QuartzCompressed)
			.AddProductToUnlock(PackingModIds.Products.RockCompressed)
			.AddProductToUnlock(PackingModIds.Products.SaltCompressed)
			.AddProductToUnlock(PackingModIds.Products.SandCompressed)
			.AddProductToUnlock(PackingModIds.Products.SlagCrushedCompressed)
			.AddProductToUnlock(PackingModIds.Products.SlagCompressed)
			.AddProductToUnlock(PackingModIds.Products.SludgeCompressed)
			.AddProductToUnlock(PackingModIds.Products.SoyBeansCompressed)
			.AddProductToUnlock(PackingModIds.Products.SugarcaneCompressed)
			.AddProductToUnlock(PackingModIds.Products.SugarCompressed)
			.AddProductToUnlock(PackingModIds.Products.SulfurCompressed)
			.AddProductToUnlock(PackingModIds.Products.UraniumOreCrushedCompressed)
			.AddProductToUnlock(PackingModIds.Products.UraniumOreCompressed)
			.AddProductToUnlock(PackingModIds.Products.WheatCompressed)
			.AddProductToUnlock(PackingModIds.Products.YellowcakeCompressed)
			.AddProductToUnlock(PackingModIds.Products.WasteCompressed)
			//.AddProductToUnlock(PackingModIds.Products.ExampleFluidProduct)
			//.AddProductToUnlock(PackingModIds.Products.ExampleUnitProduct)
			//.AddProductToUnlock(PackingModIds.Products.ExampleMoltenProduct)
			.AddRecipeToUnlock(PackingModIds.Recipes.Packing_1)
			.AddRecipeToUnlock(PackingModIds.Recipes.Packing_2)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_3)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_4)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_5)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_6)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_7)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_8)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_9)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_10)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_11)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_12)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_13)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_14)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_15)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_16)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_17)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_18)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_19)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_20)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_21)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_22)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_23)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_24)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_25)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_26)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_27)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_28)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_29)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_30)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_31)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_32)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_33)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_34)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_35)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_36)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_38)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_39)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_40)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_41)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_42)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_43)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_44)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_45)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_46)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_47)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_48)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_49)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_50)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_51)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_52)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_53)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_54)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_55)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_56)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_57)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_58)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_59)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_60)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_61)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_62)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_63)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_64)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_65)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_66)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_67)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_68)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_69)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_70)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_71)
.AddRecipeToUnlock(PackingModIds.Recipes.Packing_72)


			.AddMachineToUnlock(PackingModIds.Machines.Packager)
			.BuildAndAdd();

		nodeProto.GridPosition = new Vector2i(4, 31);
		nodeProto.AddParent(registrator.PrototypesDb.GetOrThrow<ResearchNodeProto>(Ids.Research.BasicFarming));

	}

}